export const Anxiety = {
    heading: "Anxiety Test",
    type: [
        {
            id: 1,
            question: "1. Feeling nervous, anxious, or on edge",
            option1: "NOT AT ALL",
            option2: "SEVERAL DAYS",
            option3: "MORE THAN HALF THE DAYS",
            option4: "NEARLY EVERY DAY",
        },
        {
            id: 2,
            question: "2. Not being able to stop or control worrying",
            option1: "NOT AT ALL",
            option2: "SEVERAL DAYS",
            option3: "MORE THAN HALF THE DAYS",
            option4: "NEARLY EVERY DAY",
        },
        {
            id: 3,
            question: "3. Worrying too much about different things",
            option1: "NOT AT ALL",
            option2: "SEVERAL DAYS",
            option3: "MORE THAN HALF THE DAYS",
            option4: "NEARLY EVERY DAY",
        },
        {
            id: 4,
            question: "4. Trouble relaxing",
            option1: "NOT AT ALL",
            option2: "SEVERAL DAYS",
            option3: "MORE THAN HALF THE DAYS",
            option4: "NEARLY EVERY DAY",
        },
        {
            id: 5,
            question: "5. Being so restless that it is hard to sit still",
            option1: "NOT AT ALL",
            option2: "SEVERAL DAYS",
            option3: "MORE THAN HALF THE DAYS",
            option4: "NEARLY EVERY DAY",
        },
        {
            id: 6,
            question: "6. Becoming easily annoyed or irritable",
            option1: "NOT AT ALL",
            option2: "SEVERAL DAYS",
            option3: "MORE THAN HALF THE DAYS",
            option4: "NEARLY EVERY DAY",
        },
        {
            id: 7,
            question: "7. Feeling afraid, as if something awful might happen",
            option1: "NOT AT ALL",
            option2: "SEVERAL DAYS",
            option3: "MORE THAN HALF THE DAYS",
            option4: "NEARLY EVERY DAY",
        },
    ]
}