export const DepressionForNew = {
    heading: "Depression Test for New and Expecting Parents",
    type: [{
        id: 1,
        question: "1. I have been able to laugh and see the funny side of things",
        option1: "AS MUCH AS I ALWAYS COULD",
        option2: "NOT QUITE SO MUCH NOW",
        option3: "DEFINITELY NOT SO MUCH NOW",
        option4: "NOT AT ALL",
    },
    {
        id: 2,
        question: "2. I have looked forward with enjoyment to things",
        option1: "AS MUCH AS I EVER DID",
        option2: "RATHER LESS THAN I USED TO",
        option3: "DEFINITELY LESS THAN I USED TO",
        option4: "HARDLY AT ALL",
    },
    {
        id: 3,
        question: "3. I have blamed myself unnecessarily when things went wrong",
        option1: "YES, MOST OF THE TIME",
        option2: "YES, SOME OF THE TIME",
        option3: "NOT VERY OFTEN",
        option4: "NO, NEVER",
    },
    {
        id: 4,
        question: "4. I have been anxious or worried for no good reason",
        option1: "NO, NOT AT ALL",
        option2: "HARDLY EVER",
        option3: "YES, SOMETIMES",
        option4: "YES, VERY OFTEN",
    },
    {
        id: 5,
        question: "5. I have felt scared or panicky for no very good reason",
        option1: "YES, QUITE A LOT",
        option2: "YES, SOMETIMES",
        option3: "NO, NOT MUCH",
        option4: "NO, NOT AT ALL",
    },
    {
        id: 6,
        question: "6. Things have been getting on top of me",
        option1: "YES, MOST OF THE TIME I HAVEN'T BEEN ABLE TO COPE AT ALL",
        option2: "YES, SOMETIMES I HAVEN'T BEEN COPING AS WELL AS USUAL",
        option3: "NO, MOST OF THE TIME I HAVE COPED QUITE WELL",
        option4: "NO, I HAVE BEEN COPING AS WELL AS EVER",
    },
    {
        id: 7,
        question: "7. I have been so unhappy that I have had difficulty sleeping",
        option1: "YES, MOST OF THE TIME",
        option2: "YES, SOMETIMES",
        option3: "NOT VERY OFTEN",
        option4: "NO, NOT AT ALL",
    },
    {
        id: 8,
        question: "8. I have felt sad or miserable",
        option1: "YES, MOST OF THE TIME",
        option2: "YES, QUITE OFTEN",
        option3: "NOT VERY OFTEN",
        option4: "NO, NOT AT ALL",
    },
    {
        id: 9,
        question: "9. I have been so unhappy that I have been crying",
        option1: "YES, MOST OF THE TIME",
        option2: "YES, QUITE OFTEN",
        option3: "ONLY OCCASIONALLY",
        option4: "NO, NEVER",
    },
    {
        id: 10,
        question: "10. The thought of harming myself has occurred to me",
        option1: "YES, QUITE OFTEN",
        option2: "SOMETIMES",
        option3: "HARDLY EVER",
        option4: "NEVER",
    },
    ]
}