export const Depression =
{
  heading: "Depression Test",
  type: [{
    id: 1,
    question: "1. Little interest or pleasure in doing things",
    option1: "NOT AT ALL",
    option2: "SEVERAL DAYS",
    option3: "MORE THAN HALF THE DAYS",
    option4: "NEARLY EVERY DAY",
  },
  {
    id: 2,
    question: "2. Feeling down, depressed, or hopeless",
    option1: "NOT AT ALL",
    option2: "SEVERAL DAYS",
    option3: "MORE THAN HALF THE DAYS",
    option4: "NEARLY EVERY DAY",
  },
  {
    id: 3,
    question: "3. Trouble falling or staying asleep, or sleeping too much",
    option1: "NOT AT ALL",
    option2: "SEVERAL DAYS",
    option3: "MORE THAN HALF THE DAYS",
    option4: "NEARLY EVERY DAY",
  },
  {
    id: 4,
    question: "4. Feeling tired or having little energy",
    option1: "NOT AT ALL",
    option2: "SEVERAL DAYS",
    option3: "MORE THAN HALF THE DAYS",
    option4: "NEARLY EVERY DAY",
  },
  {
    id: 5,
    question: "5. Poor appetite or overeating",
    option1: "NOT AT ALL",
    option2: "SEVERAL DAYS",
    option3: "MORE THAN HALF THE DAYS",
    option4: "NEARLY EVERY DAY",
  },
  {
    id: 6,
    question: "6. Feeling bad about yourself - or that you are a failure or have let yourself or your family down",
    option1: "NOT AT ALL",
    option2: "SEVERAL DAYS",
    option3: "MORE THAN HALF THE DAYS",
    option4: "NEARLY EVERY DAY",
  },
  {
    id: 7,
    question: "7. Trouble concentrating on things, such as reading the newspaper or watching television",
    option1: "NOT AT ALL",
    option2: "SEVERAL DAYS",
    option3: "MORE THAN HALF THE DAYS",
    option4: "NEARLY EVERY DAY",
  },
  {
    id: 8,
    question: "8. Moving or speaking so slowly that other people could have noticed Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual",
    option1: "NOT AT ALL",
    option2: "SEVERAL DAYS",
    option3: "MORE THAN HALF THE DAYS",
    option4: "NEARLY EVERY DAY",
  },
  {
    id: 9,
    question: "9. Thoughts that you would be better off dead, or of hurting yourself",
    option1: "NOT AT ALL",
    option2: "SEVERAL DAYS",
    option3: "MORE THAN HALF THE DAYS",
    option4: "NEARLY EVERY DAY",
  },
  {
    id: 10,
    question: "10. If you checked off any problems, how difficult have these problems made it for you at work, home, or with other people?",
    option1: "NOT DIFFICULT AT ALL",
    option2: "SOMEWHAT DIFFICULT",
    option3: "VERY DIFFICULT",
    option4: "EXTREMELY DIFFICULT",
  },
  ],
}

